### ISSUE TITLE
活跃检测功能不正常

### ISSUE THREAD

**Issue by somiio** [berry8838/Sakura_embyboss#12]
使用/low_activity指令进行手动活跃检测，出现两个问题
1。绑定tg频道 活跃检测禁用会频道通知，每次只会出现20条消息。后续无消息推送。无法观察是否继续进行检测。手动重启bot重新使用指令检测 重新推送20条消息。观察应该没有继续检测。

2。观察发现活跃检测删除起始计算时间好像不是禁用时间。
按检测 重启 检测 顺序 前一次禁用的账户会在第二次检测删除。

**Comment by berry8838** [comment]
好的，收到了，关于第二个问题，是，禁用之后，会在第二天8点半删除，不是马上删除的，因为禁用是禁用，删除是删除。这是正常的。至于第一个问题，最好能提供一下log哈。

**Comment by berry8838** [comment]
嗯，好的，只是bot发的信息太快了，触发了flood，会处理一下哈

**Comment by berry8838** [comment]
> > 好的，收到了，关于第二个问题，是，禁用之后，会在第二天8点半删除，不是马上删除的，因为禁用是禁用，删除是删除。这是正常的。至于第一个问题，最好能提供一下log哈。
> 
> `2023-10-16 19:34:46,374 - pyrogram.dispatcher - ERROR - Telegram says: [420 FLOOD_WAIT_X] - A wait of 39 seconds is required (caused by "messages.SendMessage") Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker await handler.callback(self.client, *args) File "/usr/local/lib/python3.9/dist-packages/pyromod/listen/listen.py", line 237, in resolve_future await self.registered_handler(client, message, *args) File "/root/Sakura_embyboss/bot/modules/userplays_rank.py", line 127, in run_low_ac await check_low_activity() File "/root/Sakura_embyboss/bot/modules/userplays_rank.py", line 104, in check_low_activity await bot.send_message(chat_id=group[0], File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/messages/send_message.py", line 126, in send_message r = await self.invoke( File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke r = await self.session.invoke( File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 389, in invoke return await self.send(query, timeout=timeout) File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 357, in send RPCError.raise_it(result, type(data)) File "/usr/local/lib/python3.9/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it raise getattr( pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 39 seconds is required (caused by "messages.SendMessage") 2023-10-16 21:10:30,361 - bot -`
> 
> 这是开始定期任务的二十条信息后的log

已修复。有后续请反馈
