### ISSUE TITLE
[错误报告] 在使用过程中经常遇到 pyrogram.dispatcher - ERROR - 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by hsuyelin** [berry8838/Sakura_embyboss#13]
环境：docker
版本：48f441fd121c
系统：debian11
python版本：python3.10
日志：
[log_2023-10-19.txt](https://github.com/berry8838/Sakura_embyboss/files/13044530/log_2023-10-19.txt)

**Comment by berry8838** [comment]
listen does not check if message.from_user.id exists or not.  应该是这个问题吧，是因为依赖pyromod没更新到最新版所以存在的问题hhhh，现在写到了requirement.txt里面了。换最新版的试试吧~

**Comment by hsuyelin** [comment]
我试试 @berry8838

**Comment by hsuyelin** [comment]
貌似好了，感谢
