### ISSUE TITLE
invite表的used和usedtime字段不会更新，导致卡密可重复使用

### ISSUE THREAD

**Issue by aa342138039** [berry8838/Sakura_embyboss#2]
![image](https://github.com/berry8838/Sakura_embyboss/assets/31955300/74d96b29-2f76-4501-ace2-c62c645b163c)
****

![image](https://github.com/berry8838/Sakura_embyboss/assets/31955300/0ae318ea-f77d-4175-a727-3007a925a73a)

**Comment by aa342138039** [comment]
> ![image](https://user-images.githubusercontent.com/89853825/242620020-35dada57-e071-42de-b8e2-1e7b3d11623e.png) 额，看看log铁纸。

2023-06-01 21:57:42,539 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 
2023-06-01 21:57:44,011 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 
2023-06-01 21:57:45,240 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 
2023-06-01 21:57:45,799 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 
2023-06-01 21:58:05,381 - INFO - 47 - Connecting... 
2023-06-01 21:58:05,418 - INFO - 54 - Connected! Production DC5 (media) - IPv4 
2023-06-01 21:58:05,419 - INFO - 294 - NetworkTask started 
2023-06-01 21:58:05,627 - INFO - 139 - Session initialized: Layer 158 
2023-06-01 21:58:05,628 - INFO - 140 - Device: CPython 3.9.2 - Pyrogram 2.0.106 
2023-06-01 21:58:05,628 - INFO - 141 - System: Linux 5.10.0-19-amd64 (en) 
2023-06-01 21:58:05,628 - INFO - 155 - Session started 

![image](https://github.com/berry8838/Sakura_embyboss/assets/31955300/2a4f0a0f-c29f-4aec-b2f0-1a66f6ceaccf)


日志只打印了这些

**Comment by aa342138039** [comment]
环境：debian 11      mysql：5.7      python：3.9.2

**Comment by berry8838** [comment]
> > ![image](https://user-images.githubusercontent.com/89853825/242620020-35dada57-e071-42de-b8e2-1e7b3d11623e.png) 额，看看log铁纸。
> 
> 2023-06-01 21:57:42,539 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 2023-06-01 21:57:44,011 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 2023-06-01 21:57:45,240 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 2023-06-01 21:57:45,799 - INFO - 138 - 【兑换码】：55183513 使用了 OvO-01-e340cfb1b448416c84b45bd829accace 2023-06-01 21:58:05,381 - INFO - 47 - Connecting... 2023-06-01 21:58:05,418 - INFO - 54 - Connected! Production DC5 (media) - IPv4 2023-06-01 21:58:05,419 - INFO - 294 - NetworkTask started 2023-06-01 21:58:05,627 - INFO - 139 - Session initialized: Layer 158 2023-06-01 21:58:05,628 - INFO - 140 - Device: CPython 3.9.2 - Pyrogram 2.0.106 2023-06-01 21:58:05,628 - INFO - 141 - System: Linux 5.10.0-19-amd64 (en) 2023-06-01 21:58:05,628 - INFO - 155 - Session started
> 
> ![image](https://user-images.githubusercontent.com/31955300/242620954-2a4f0a0f-c29f-4aec-b2f0-1a66f6ceaccf.png)
> 
> 日志只打印了这些
欧克，我初步估计是，应该是我数据库建立时没考虑到新号的tgid长度，我稍后去看看我的表，然后再更新。

**Comment by aa342138039** [comment]
@berry8838 

不是，老哥，日志中的tgid我剔了2位。   打了个码

**Comment by berry8838** [comment]
> @berry8838
> 
> 不是，老哥，日志中的tgid我剔了2位。 打了个码

![image](https://github.com/berry8838/Sakura_embyboss/assets/89853825/81292419-96ef-45c9-a044-77910f7489e0)
我的意思是在invite表中，需要在 - 结构 - 把 tg 和 used 字段设置成 bigint(255)

**Comment by aa342138039** [comment]
> > @berry8838
> > 不是，老哥，日志中的tgid我剔了2位。 打了个码
> 
> ![image](https://user-images.githubusercontent.com/89853825/242626800-81292419-96ef-45c9-a044-77910f7489e0.png) 我的意思是在invite表中，需要在 - 结构 - 把 tg 和 used 字段设置成 bigint(255)

![image](https://github.com/berry8838/Sakura_embyboss/assets/31955300/557d23a8-9b5d-4ad2-b608-21ab11949156)
![image](https://github.com/berry8838/Sakura_embyboss/assets/31955300/b3a37c2a-51d7-4cb8-a99b-81c28ed87308)

搞定，辛苦了。

**Comment by berry8838** [comment]
> > > @berry8838
> > > 不是，老哥，日志中的tgid我剔了2位。 打了个码
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/89853825/242626800-81292419-96ef-45c9-a044-77910f7489e0.png) 我的意思是在invite表中，需要在 - 结构 - 把 tg 和 used 字段设置成 bigint(255)
> 
> ![image](https://user-images.githubusercontent.com/31955300/242629169-557d23a8-9b5d-4ad2-b608-21ab11949156.png) ![image](https://user-images.githubusercontent.com/31955300/242629707-b3a37c2a-51d7-4cb8-a99b-81c28ed87308.png)
> 
> 搞定，辛苦了。

感谢反馈，我close咯。
