### ISSUE TITLE
关于线路切换的代码

### ISSUE THREAD

**Issue by Closty** [berry8838/Sakura_embyboss#21]
看很多服都有线路切换功能，用的是您的机器人，请问在哪里找到相关代码？谢谢！

**Comment by berry8838** [comment]
有的服前后端分离，有的服没有，不好统一，所以没写。我觉得原理如下，用户数据库里面新建一个字段表示当前的线路，然后在播放后端的代码里面，加入每次播放都查询一次数据库的当前线路。至于切换线路，即可用一些按钮表示线路，当点击按钮时触发update数据库里面的当前线路这样。我这里没有相关代码。
