### ISSUE TITLE
能否新增一个显示或者关闭NSFW内容的选项

### ISSUE THREAD

**Issue by hsuyelin** [berry8838/Sakura_embyboss#3]

**Comment by berry8838** [comment]
可以。
但是目前有两种想法

1、我会将它加到 /config 的面板中，然后需要owner在config面板点击【设置隐藏/显示内容， 回复设置对应想要设置隐藏/显示的emby分类的名字，多个分类用空格隔开。接着给用户一个命令或者按钮，让其可以自己控制 隐藏或显示 已经被管理员设定好的库。

2、给用户一个命令或者按钮，触发时 回复设置对应想要设置隐藏/显示的emby分类的名字，多个分类用空格隔开。自己控制任意 显示/隐藏的emby分类。

就是1、管理员来指定可以隐藏/显示的库  还是  2、用户使用的时候自己设置指定库

**Comment by berry8838** [comment]
done，我采用了第一中 = =
