### ISSUE TITLE
你好 为啥没有介绍说的功能？

### ISSUE THREAD

**Issue by owo10086** [berry8838/Sakura_embyboss#9]
用户面板
 创建账户
 绑定未登记账户、换绑TG
 兑换注册码
 重置密码

**Comment by berry8838** [comment]
啊？你搭建可能有失误。
![image](https://github.com/berry8838/Sakura_embyboss/assets/89853825/66a0d686-302b-4f8b-9c76-024ec45924b7)

**Comment by owo10086** [comment]
> 啊？你搭建可能有失误。 ![image](https://user-images.githubusercontent.com/89853825/260218525-66a0d686-302b-4f8b-9c76-024ec45924b7.png)

我只有这些功能，没看到开户呢
![1afd2844126489d1189e5.jpg](https://telegra.ph/file/1afd2844126489d1189e5.jpg)
![7fe8da82bd9092d8f395a.jpg](https://telegra.ph/file/7fe8da82bd9092d8f395a.jpg)
![6304457a75fbbc693f59b.jpg](https://telegra.ph/file/6304457a75fbbc693f59b.jpg)
![057cfba083791e8ac970b.jpg](https://telegra.ph/file/057cfba083791e8ac970b.jpg)
![8bbe558407a2627b56056.jpg](https://telegra.ph/file/8bbe558407a2627b56056.jpg)
日志貌似也没报错，我是用docker运行的
![2f32dccd671b3d89e1266.png](https://telegra.ph/file/2f32dccd671b3d89e1266.png)
![296a8f049cb820a4ed8fe.png](https://telegra.ph/file/296a8f049cb820a4ed8fe.png)
还是说需要花钱购买bot？

**Comment by berry8838** [comment]
手把手教你吧  https://t.me/Aaaaa_su
